name: Run ESLint on Pull Requests

on:
  - push

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm i

      - run: npm run format

      - run: npm run lint

      - run: npm test
